class Options:
    CHROMOSOME_LENGTH = 51
    POPULATION_SIZE = 100
    MAX_GENERATION = 200
    P_CROSS = 0.667
    P_MUT = 0.001
    CHC_LAMDA = 2
    RANDOM_SEED = 200
    EVALUATOR = None
    TOTAL_RUNS = 1
    OBJECTIVE = None
# 67